In [1]:
import csv
import random
from datetime import datetime, timedelta

# ============================================================
# إعدادات الملف
# ============================================================

file_path = "twenty_million_messy_trips.csv"
total_rows = 10_000_000

# قيم الفوضى المقصودة
statuses = [
    "Completed",
    "completed",
    "COMPLETED",
    " Cancelled ",
    "failed",
    "NULL",
    "NaN",
    "Unknown"
]

cities = [
    "Khartoum",
    " Khartoum ",
    "Omdurman",
    "Bahri",
    "Port Sudan"
]

phones = [
    "0912345678",
    "00249912345678",
    "+249912345678",
    "N/A",
    "09-123-4567"
]

devices = [
    '{"os": "Android", "app_version": "5.1.2"}',
    '{"os": "iOS", "app_version": "5.1.0"}',
    '{"os": "Huawei", "app_version": "4.9.0"}',
    '{}',
    'NULL'
]

headers = [
    "trip_id",
    "driver_id",
    "customer_id",
    "start_time",
    "end_time",
    "distance_km",
    "fare_amount",
    "status",
    "phone_number",
    "device_info",
    "city"
]

print(f"⏳ بدء توليد {total_rows:,} سطر بيانات فوضوية...")

base_time = datetime(2026, 1, 1)

with open(
    file_path,
    mode="w",
    newline="",
    encoding="utf-8"
) as f:

    writer = csv.writer(f)
    writer.writerow(headers)

    for i in range(1, total_rows + 1):

        # ====================================================
        # 1. trip_id
        # ====================================================

        id_rand = random.random()

        if id_rand < 0.005:
            # Missing trip_id
            trip_id = ""

        elif id_rand < 0.015:
            # Duplicate trip_id
            trip_id = f"TRIP_{max(1, i - 10)}"

        else:
            trip_id = f"TRIP_{i}"

        # ====================================================
        # 2. Driver / Customer IDs
        # ====================================================

        if random.random() < 0.01:

            # Orphan references
            driver_id = "DRV_999999"
            customer_id = "CST_999999"

        else:

            driver_id = f"DRV_{random.randint(1, 1000)}"
            customer_id = f"CST_{random.randint(1, 5000)}"

        # ====================================================
        # 3. Timestamps
        # ====================================================

        start_date = base_time + timedelta(
            seconds=i * 0.1
        )

        time_rand = random.random()

        if time_rand < 0.005:

            # Invalid duration:
            # end < start
            end_date = start_date - timedelta(
                minutes=random.randint(10, 60)
            )

        elif time_rand < 0.01:

            # Future trip
            start_date = datetime(2030, 12, 31)

            end_date = start_date + timedelta(
                minutes=15
            )

        else:

            # Normal trip
            end_date = start_date + timedelta(
                minutes=random.randint(5, 45)
            )

        start_time_str = start_date.strftime(
            "%Y-%m-%d %H:%M:%S"
        )

        end_time_str = end_date.strftime(
            "%Y-%m-%d %H:%M:%S"
        )

        # ====================================================
        # 4. Distance
        # ====================================================

        distance = round(
            random.uniform(0.5, 500),
            2
        )

        if random.random() < 0.01:
            distance = -abs(distance)

        # ====================================================
        # 5. Fare
        # ====================================================

        fare = round(
            random.uniform(50, 1500),
            2
        )

        # Create a few extreme values
        if random.random() < 0.01:
            fare = random.choice([
                -abs(fare),
                100000,
                500000,
                1000000
            ])

        # ====================================================
        # 6. Other messy attributes
        # ====================================================

        status = random.choice(statuses)
        phone = random.choice(phones)
        device_info = random.choice(devices)
        city = random.choice(cities)

        # ====================================================
        # 7. Write row
        # ====================================================

        writer.writerow([
            trip_id,
            driver_id,
            customer_id,
            start_time_str,
            end_time_str,
            distance,
            fare,
            status,
            phone,
            device_info,
            city
        ])

        # Progress
        if i % 500_000 == 0:
            print(
                f"✅ تم إنشاء {i:,} / {total_rows:,} صف"
            )

print(
    f"✅ اكتمل توليد الملف: {file_path}"
)

⏳ بدء توليد 10,000,000 سطر بيانات فوضوية...
✅ تم إنشاء 500,000 / 10,000,000 صف
✅ تم إنشاء 1,000,000 / 10,000,000 صف
✅ تم إنشاء 1,500,000 / 10,000,000 صف
✅ تم إنشاء 2,000,000 / 10,000,000 صف
✅ تم إنشاء 2,500,000 / 10,000,000 صف
✅ تم إنشاء 3,000,000 / 10,000,000 صف
✅ تم إنشاء 3,500,000 / 10,000,000 صف
✅ تم إنشاء 4,000,000 / 10,000,000 صف
✅ تم إنشاء 4,500,000 / 10,000,000 صف
✅ تم إنشاء 5,000,000 / 10,000,000 صف
✅ تم إنشاء 5,500,000 / 10,000,000 صف
✅ تم إنشاء 6,000,000 / 10,000,000 صف
✅ تم إنشاء 6,500,000 / 10,000,000 صف
✅ تم إنشاء 7,000,000 / 10,000,000 صف
✅ تم إنشاء 7,500,000 / 10,000,000 صف
✅ تم إنشاء 8,000,000 / 10,000,000 صف
✅ تم إنشاء 8,500,000 / 10,000,000 صف
✅ تم إنشاء 9,000,000 / 10,000,000 صف
✅ تم إنشاء 9,500,000 / 10,000,000 صف
✅ تم إنشاء 10,000,000 / 10,000,000 صف
✅ اكتمل توليد الملف: twenty_million_messy_trips.csv

In [3]:
import duckdb

con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

con.execute("DROP TABLE IF EXISTS main.my_clean_table;")

con.execute("""
CREATE TABLE main.my_clean_table AS
SELECT
    CAST(trip_id AS VARCHAR) AS trip_id,
    CAST(driver_id AS VARCHAR) AS driver_id,
    CAST(customer_id AS VARCHAR) AS customer_id,

    TRY_CAST(start_time AS TIMESTAMP) AS start_time,
    TRY_CAST(end_time AS TIMESTAMP) AS end_time,

    TRY_CAST(distance_km AS DOUBLE) AS distance_km,

    TRY_CAST(
        REPLACE(fare_amount, ',', '')
        AS DOUBLE
    ) AS fare_amount,

    CAST(status AS VARCHAR) AS status,
    CAST(phone_number AS VARCHAR) AS phone_number,
    CAST(device_info AS VARCHAR) AS device_info,
    CAST(city AS VARCHAR) AS city

FROM read_csv(
    'twenty_million_messy_trips.csv',
    HEADER = TRUE,
    ALL_VARCHAR = TRUE
);
""")

total = con.execute("""
SELECT COUNT(*)
FROM main.my_clean_table;
""").fetchone()[0]

print(f"✅ تم تحميل الملف بالكامل: {total:,} صف")

✅ تم تحميل الملف بالكامل: 10,000,000 صف

In [4]:
import duckdb

# فتح الاتصال بالمستودع الصلب على الهارد ديسك
con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

# 2. كود الـ SQL المباشر لجلب عينة أول 5 أسطر فقط 
Having = """
SELECT trip_id, COUNT(*) 
FROM main.my_clean_table
WHERE trip_id IS NOT NULL AND trip_id != ''
GROUP BY trip_id
HAVING COUNT(*) > 1
LIMIT 10;
"""

# 3. طحن العينة وتحويلها لجدول بايثون (Pandas) للعرض البصري الأنيق
result_Having = con.execute(Having).df()

# 5. عرض العينة المكونة من 5 صفوف في النوت بوك
display(result_Having)

     trip_id  count_star()
0    TRIP_16             2
1   TRIP_104             2
2   TRIP_355             2
3   TRIP_609             2
4  TRIP_1042             2
5  TRIP_1150             2
6  TRIP_1220             2
7  TRIP_1405             2
8  TRIP_1574             2
9  TRIP_1626             2

In [5]:
import duckdb

# 1. فتح اتصال في ملف حقيقي على الهارد ديسك السريع لمنع اختناق الـ RAM
con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

Having2 = ("""
    SELECT trip_id, COUNT(*)
    FROM main.my_clean_table
    WHERE trip_id IS NOT NULL AND trip_id != ''
    GROUP BY trip_id
    HAVING COUNT(*) > 1
    LIMIT 10;
""")

# 3. طحن العينة وتحويلها لجدول بايثون (Pandas) للعرض البصري الأنيق
result_Having2 = con.execute(Having2).df()

# 5. عرض العينة المكونة من 5 صفوف في النوت بوك
display(result_Having2)

       trip_id  count_star()
0  TRIP_111906             2
1  TRIP_112177             2
2  TRIP_112184             2
3  TRIP_112198             2
4  TRIP_112423             2
5  TRIP_112598             2
6  TRIP_112767             2
7  TRIP_113222             2
8  TRIP_113278             2
9  TRIP_113406             2

In [6]:
import duckdb

# 1. فتح اتصال في ملف حقيقي على الهارد ديسك السريع لمنع اختناق الـ RAM
con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

Having2 = ("""
    SELECT trip_id, COUNT(*)
    FROM main.my_clean_table
    WHERE trip_id IS NOT NULL AND trip_id != ''
    GROUP BY trip_id
    HAVING COUNT(*) > 1
    LIMIT 10;
""")

# 3. طحن العينة وتحويلها لجدول بايثون (Pandas) للعرض البصري الأنيق
result_Having2 = con.execute(Having2).df()

# 5. عرض العينة المكونة من 5 صفوف في النوت بوك
display(result_Having2)

     trip_id  count_star()
0    TRIP_16             2
1   TRIP_104             2
2   TRIP_355             2
3   TRIP_609             2
4  TRIP_1042             2
5  TRIP_1150             2
6  TRIP_1220             2
7  TRIP_1405             2
8  TRIP_1574             2
9  TRIP_1626             2

In [7]:
import duckdb

# 1. فتح اتصال في ملف حقيقي على الهارد ديسك السريع لمنع اختناق الـ RAM
con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

Having3 = ("""
    SELECT COUNT(*)
    FROM main.my_clean_table
    WHERE trip_id IS NULL OR TRIM(trip_id) = ''
    LIMIT 10;
""")

# 3. طحن العينة وتحويلها لجدول بايثون (Pandas) للعرض البصري الأنيق
result_Having3 = con.execute(Having3).df()

# 5. عرض العينة المكونة من 5 صفوف في النوت بوك
display(result_Having3)

   count_star()
0         50124

In [8]:
import duckdb

con = duckdb.connect(
    database="/tmp/enterprise_warehouse.duckdb"
)

con.execute("""
CREATE OR REPLACE VIEW main.v_step1_durations AS

SELECT *
FROM main.my_clean_table

WHERE trip_id IS NOT NULL
  AND TRIM(trip_id) != ''
  AND LOWER(TRIM(trip_id)) NOT IN ('null', 'nan', 'none')

QUALIFY ROW_NUMBER() OVER (
    PARTITION BY TRIM(trip_id)
    ORDER BY start_time DESC NULLS LAST
) = 1;
""")

print("✅ Step 1: duplicate trip_id records resolved.")

✅ Step 1: duplicate trip_id records resolved.

In [9]:
import duckdb

# 1. فتح اتصال في ملف حقيقي على الهارد ديسك السريع لمنع اختناق الـ RAM
con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

Timestamp = ("""
SELECT trip_id, start_time, end_time
FROM main.v_step1_durations
WHERE end_time < start_time
LIMIT 10;
""")

# 3. طحن العينة وتحويلها لجدول بايثون (Pandas) للعرض البصري الأنيق
result_Timestamp = con.execute(Timestamp).df()

# 5. عرض العينة المكونة من 5 صفوف في النوت بوك
display(result_Timestamp)

        trip_id          start_time            end_time
0  TRIP_1009851 2026-01-02 04:03:05 2026-01-02 03:48:05
1   TRIP_102267 2026-01-01 02:50:26 2026-01-01 02:22:26
2  TRIP_1045627 2026-01-02 05:02:42 2026-01-02 04:20:42
3  TRIP_1050197 2026-01-02 05:10:19 2026-01-02 04:15:19
4  TRIP_1058511 2026-01-02 05:24:11 2026-01-02 05:09:11
5  TRIP_1079243 2026-01-02 05:58:44 2026-01-02 05:07:44
6  TRIP_1104949 2026-01-02 06:41:34 2026-01-02 05:41:34
7   TRIP_112134 2026-01-01 03:06:53 2026-01-01 02:23:53
8  TRIP_1132682 2026-01-02 07:27:48 2026-01-02 06:50:48
9   TRIP_113610 2026-01-01 03:09:21 2026-01-01 02:35:21

In [10]:
import duckdb

con = duckdb.connect(
    database="/tmp/enterprise_warehouse.duckdb"
)

con.execute("""
CREATE OR REPLACE VIEW main.v_step2_durations AS

SELECT
    trip_id,
    driver_id,
    customer_id,
    start_time,

    CASE
        WHEN end_time >= start_time
        THEN end_time
        ELSE NULL
    END AS end_time,

    distance_km,
    fare_amount,
    status,
    phone_number,
    device_info,
    city

FROM main.v_step1_durations;
""")

print("✅ Step 2: invalid end_time values converted to NULL.")

✅ Step 2: invalid end_time values converted to NULL.

In [11]:
import duckdb
con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

# الخطوة 1: حذف التكرارات والقيم الفارغة للمعرف
df_future = con.execute("""
SELECT trip_id, start_time
FROM main.v_step2_durations
WHERE start_time > NOW()
LIMIT 10;
""").df()

display(df_future)
print("مشاكل الزمن الاستكشاف الثاني ")

        trip_id start_time
0  TRIP_1019441 2030-12-31
1  TRIP_1031078 2030-12-31
2  TRIP_1074234 2030-12-31
3  TRIP_1098725 2030-12-31
4  TRIP_1111067 2030-12-31
5  TRIP_1111087 2030-12-31
6  TRIP_1129456 2030-12-31
7  TRIP_1137318 2030-12-31
8  TRIP_1148409 2030-12-31
9  TRIP_1163562 2030-12-31

مشاكل الزمن الاستكشاف الثاني

In [12]:
import duckdb
con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

# الخطوة 1: حذف التكرارات والقيم الفارغة للمعرف
con.execute("""
CREATE OR REPLACE VIEW  main.v_step3_future_trips AS
SELECT *
FROM main.v_step2_durations
WHERE start_time <= NOW();
""")
print("مشاكل الزمن الحل الثاني ")



df_future_sample = con.execute(
    """
SELECT trip_id, start_time, end_time, city
FROM main.v_step3_future_trips
LIMIT 10;
"""
).df()

# 3. العرض البصري للنوت بوك
display(df_future_sample)

مشاكل الزمن الحل الثاني

        trip_id          start_time            end_time        city
0  TRIP_1000008 2026-01-02 03:46:40 2026-01-02 04:13:40       Bahri
1  TRIP_1000051 2026-01-02 03:46:45 2026-01-02 04:30:45       Bahri
2   TRIP_100014 2026-01-01 02:46:41 2026-01-01 03:09:41       Bahri
3  TRIP_1000230 2026-01-02 03:47:03 2026-01-02 04:21:03    Omdurman
4  TRIP_1000283 2026-01-02 03:47:08 2026-01-02 04:23:08  Port Sudan
5  TRIP_1000303 2026-01-02 03:47:10 2026-01-02 04:08:10  Port Sudan
6  TRIP_1000727 2026-01-02 03:47:52 2026-01-02 04:10:52       Bahri
7  TRIP_1000826 2026-01-02 03:48:02 2026-01-02 04:16:02  Port Sudan
8  TRIP_1001047 2026-01-02 03:48:24 2026-01-02 04:25:24  Port Sudan
9   TRIP_100127 2026-01-01 02:46:52 2026-01-01 03:27:52    Omdurman

In [13]:
import duckdb
con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

# الخطوة 1: حذف التكرارات والقيم الفارغة للمعرف
df_future1 = con.execute("""
SELECT driver_id, start_time, COUNT(*) 
FROM main.v_step3_future_trips
GROUP BY driver_id, start_time
HAVING COUNT(*) > 1
LIMIT 10;
""").df()

display(df_future1)
print("مشاكل الزمن الاستكشاف الثالث ")

    driver_id          start_time  count_star()
0     DRV_759 2026-01-02 03:56:20             2
1     DRV_485 2026-01-01 02:53:47             2
2     DRV_336 2026-01-02 06:00:15             2
3     DRV_910 2026-01-02 07:08:04             2
4     DRV_121 2026-01-02 07:09:32             2
5     DRV_336 2026-01-02 07:09:47             2
6  DRV_999999 2026-01-02 07:55:38             3
7     DRV_424 2026-01-02 10:38:12             2
8     DRV_655 2026-01-02 10:42:48             2
9     DRV_817 2026-01-02 11:35:03             2

مشاكل الزمن الاستكشاف الثالث

In [14]:
import duckdb
con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

# الخطوة 1: حذف التكرارات والقيم الفارغة للمعرف
con.execute("""
CREATE OR REPLACE VIEW main.v_step4_overlapping_trips AS
SELECT * 
FROM main.v_step3_future_trips
QUALIFY ROW_NUMBER() OVER (PARTITION BY driver_id, start_time ORDER BY end_time DESC) = 1;
""")
print("مشاكل الزمن الحل الثالث ")



df_future_sample = con.execute("""
SELECT trip_id, start_time, end_time, driver_id
FROM main.v_step4_overlapping_trips
LIMIT 10;
"""
).df()

# 3. العرض البصري للنوت بوك
display(df_future_sample)

مشاكل الزمن الحل الثالث

        trip_id          start_time            end_time driver_id
0   TRIP_242894 2026-01-01 06:44:49 2026-01-01 06:54:49     DRV_1
1   TRIP_279103 2026-01-01 07:45:10 2026-01-01 08:27:10     DRV_1
2   TRIP_462122 2026-01-01 12:50:12 2026-01-01 13:20:12     DRV_1
3   TRIP_557108 2026-01-01 15:28:30 2026-01-01 15:33:30     DRV_1
4   TRIP_561888 2026-01-01 15:36:28 2026-01-01 15:49:28     DRV_1
5   TRIP_731897 2026-01-01 20:19:49 2026-01-01 21:00:49     DRV_1
6   TRIP_761822 2026-01-01 21:09:42 2026-01-01 21:39:42     DRV_1
7   TRIP_805075 2026-01-01 22:21:47 2026-01-01 22:47:47     DRV_1
8   TRIP_920020 2026-01-02 01:33:22 2026-01-02 01:54:22     DRV_1
9  TRIP_1525063 2026-01-02 18:21:46 2026-01-02 19:04:46     DRV_1

In [15]:
import duckdb

con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

df_negative = con.execute("""
SELECT
    COUNT(CASE WHEN fare_amount < 0 THEN 1 END) AS negative_fares_count,
    COUNT(CASE WHEN distance_km < 0 THEN 1 END) AS negative_distances_count
FROM main.v_step4_overlapping_trips;
""").df()

display(df_negative)

print("🔎 تم فحص القيم المالية والمسافات السالبة.")

   negative_fares_count  negative_distances_count
0                 24254                     97513

🔎 تم فحص القيم المالية والمسافات السالبة.

In [16]:
import duckdb

con = duckdb.connect(
    database="/tmp/enterprise_warehouse.duckdb"
)

con.execute("""
CREATE OR REPLACE VIEW main.v_step5_negative_values AS

SELECT
    trip_id,
    driver_id,
    customer_id,
    start_time,
    end_time,
    phone_number,
    device_info,
    city,
    status,
    distance_km,
    fare_amount

FROM main.v_step3_future_trips;
""")

print(
    "✅ Step 5: negative values preserved for validation; "
    "no ABS() transformation applied."
)

✅ Step 5: negative values preserved for validation; no ABS() transformation applied.

In [17]:
import duckdb
con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

# الخطوة 1: حذف التكرارات والقيم الفارغة للمعرف
df_future3 = con.execute("""
SELECT
    COUNT(CASE WHEN fare_amount > 5000 THEN 1 END) AS high_outliers_count,
    MAX(fare_amount) AS max_fare_in_data
FROM main.v_step5_negative_values
LIMIT 10;
""").df()

display(df_future3)
print("مشاكل الرحلات القيم الخياليه عرض ")

   high_outliers_count  max_fare_in_data
0                73362         1000000.0

مشاكل الرحلات القيم الخياليه عرض

In [18]:
import duckdb

con = duckdb.connect(
    database="/tmp/enterprise_warehouse.duckdb"
)

con.execute("""
CREATE OR REPLACE VIEW main.v_step6_outliers_handled AS

SELECT
    trip_id,
    driver_id,
    customer_id,
    start_time,
    end_time,
    phone_number,
    device_info,
    city,
    status,

    CASE
        WHEN distance_km > 0
        THEN distance_km
        ELSE NULL
    END AS distance_km,

    CASE
        WHEN fare_amount >= 0
        THEN fare_amount
        ELSE NULL
    END AS fare_amount

FROM main.v_step5_negative_values;
""")

print(
    "✅ Step 6: invalid negative/zero distance and negative fares "
    "converted to NULL; no arbitrary fare cap applied."
)

✅ Step 6: invalid negative/zero distance and negative fares converted to NULL; no arbitrary fare cap applied.

In [19]:
import duckdb

con = duckdb.connect(
    database="/tmp/enterprise_warehouse.duckdb"
)

df_distance_issues = con.execute("""
SELECT
    COUNT(*) FILTER (WHERE distance_km < 0) AS negative_distance,
    COUNT(*) FILTER (WHERE distance_km = 0) AS zero_distance,
    COUNT(*) FILTER (WHERE distance_km IS NULL) AS missing_distance
FROM main.v_step5_negative_values;
""").df()

display(df_distance_issues)

print("🔎 Distance quality profile completed.")

   negative_distance  zero_distance  missing_distance
0              98001              0                 0

🔎 Distance quality profile completed.

In [20]:
import duckdb
con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

# الخطوة 1: حذف التكرارات والقيم الفارغة للمعرف
con.execute("""
CREATE OR REPLACE VIEW main.v_step7_division_handled AS
SELECT
    trip_id,
    driver_id,
    customer_id,
    start_time,
    end_time,
    phone_number,
    device_info,
    city,
    status,
    distance_km,
    fare_amount,

    fare_amount / NULLIF(distance_km, 0) AS price_per_km

FROM main.v_step6_outliers_handled;
""")
print("مشاكل الرحلات 2")



df_TRAVEL = con.execute("""
SELECT *
FROM main.v_step7_division_handled
LIMIT 10;
"""
).df()

# 3. العرض البصري للنوت بوك
display(df_TRAVEL)

مشاكل الرحلات 2

,trip_id,driver_id,customer_id,start_time,end_time,phone_number,device_info,city,status,distance_km,fare_amount,price_per_km
0,TRIP_1000008,DRV_999999,CST_999999,2026-01-02 03:46:40,2026-01-02 04:13:40,0912345678,"{""os"": ""Android"", ""app_version"": ""5.1.2""}",Bahri,NaN,311.61,106.15,0.340650
1,TRIP_1000051,DRV_259,CST_3436,2026-01-02 03:46:45,2026-01-02 04:30:45,0912345678,"{""os"": ""Android"", ""app_version"": ""5.1.2""}",Bahri,completed,NaN,1465.94,NaN
2,TRIP_100014,DRV_265,CST_63,2026-01-01 02:46:41,2026-01-01 03:09:41,09-123-4567,{},Bahri,failed,139.45,1109.11,7.953460
3,TRIP_1000230,DRV_46,CST_1019,2026-01-02 03:47:03,2026-01-02 04:21:03,00249912345678,"{""os"": ""Android"", ""app_version"": ""5.1.2""}",Omdurman,NULL,194.86,296.17,1.519912
4,TRIP_1000283,DRV_792,CST_4064,2026-01-02 03:47:08,2026-01-02 04:23:08,09-123-4567,{},Port Sudan,Unknown,357.14,441.84,1.237162
5,TRIP_1000303,DRV_136,CST_503,2026-01-02 03:47:10,2026-01-02 04:08:10,00249912345678,NULL,Port Sudan,failed,45.29,1040.87,22.982336
6,TRIP_1000727,DRV_383,CST_2845,2026-01-02 03:47:52,2026-01-02 04:10:52,+249912345678,"{""os"": ""Huawei"", ""app_version"": ""4.9.0""}",Bahri,Completed,197.51,215.17,1.089413
7,TRIP_1000826,DRV_714,CST_4126,2026-01-02 03:48:02,2026-01-02 04:16:02,0912345678,"{""os"": ""iOS"", ""app_version"": ""5.1.0""}",Port Sudan,COMPLETED,167.79,942.83,5.619107
8,TRIP_1001047,DRV_126,CST_3713,2026-01-02 03:48:24,2026-01-02 04:25:24,+249912345678,"{""os"": ""Huawei"", ""app_version"": ""4.9.0""}",Port Sudan,Cancelled,288.73,157.41,0.545181
9,TRIP_100127,DRV_44,CST_748,2026-01-01 02:46:52,2026-01-01 03:27:52,N/A,"{""os"": ""Huawei"", ""app_version"": ""4.9.0""}",Omdurman,Unknown,166.25,88.71,0.533594

In [21]:
import duckdb
con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

# الخطوة 1: حذف التكرارات والقيم الفارغة للمعرف
df_future4 = con.execute("""
SELECT city, COUNT(*) 
FROM main.v_step7_division_handled 
WHERE city != TRIM(city) 
GROUP BY city;

SELECT status, COUNT(*) 
FROM main.v_step7_division_handled 
GROUP BY status
LIMIT 10;
""").df()

display(df_future4)
print("مشاكل الاحرف")

        status  count_star()
0          NaN       1223196
1      Unknown       1225048
2    completed       1227555
3       failed       1226382
4         NULL       1225650
5    Completed       1224222
6    COMPLETED       1223217
7   Cancelled        1226485

مشاكل الاحرف

In [22]:
import duckdb

con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

con.execute("""
CREATE OR REPLACE VIEW main.v_step8_text_cleaned AS
SELECT
    trip_id,
    driver_id,
    customer_id,
    start_time,
    end_time,
    phone_number,
    device_info,
    distance_km,
    fare_amount,
    price_per_km,

    TRIM(city) AS city,

    CASE
        WHEN TRIM(UPPER(status)) IN
            ('NULL', 'NAN', 'UNKNOWN', 'N/A', '')
        THEN NULL
        ELSE TRIM(UPPER(status))
    END AS status

FROM main.v_step7_division_handled;
""")

print("✅ Step 8: تم تنظيف النصوص والحالات بنجاح.")

✅ Step 8: تم تنظيف النصوص والحالات بنجاح.

In [23]:
import duckdb

con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

# استكشاف المدن التي تحتوي على رموز غريبة أو أرقام غير منطقية
df_invalid_chars = con.execute("""
SELECT city, COUNT(*) as count
FROM main.v_step8_text_cleaned
WHERE REGEXP_MATCHES(city, '[^a-zA-Z\\s]')
GROUP BY city;
""").df()

display(df_invalid_chars)

Empty DataFrame
Columns: [city, count]
Index: []

In [24]:
import duckdb

con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

df_invalid_chars1 = con.execute("""
SELECT phone_number, COUNT(*) AS count
FROM main.v_step8_text_cleaned
GROUP BY phone_number
LIMIT 10;
""").df()

display(df_invalid_chars1)

     phone_number    count
0      0912345678  1959416
1  00249912345678  1959433
2             N/A  1958233
3     09-123-4567  1962514
4   +249912345678  1962159

In [25]:
import duckdb

con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

con.execute("""
CREATE OR REPLACE VIEW main.v_step9_clean_chars AS
SELECT
    *,
    TRIM(
        REGEXP_REPLACE(
            city,
            '[^a-zA-Z ]',
            '',
            'g'
        )
    ) AS city_clean
FROM main.v_step8_text_cleaned;
""")

df_invalid_chars = con.execute("""
SELECT
    city,
    COUNT(*) AS count
FROM main.v_step8_text_cleaned
WHERE REGEXP_MATCHES(city, '[^a-zA-Z ]')
GROUP BY city;
""").df()

display(df_invalid_chars)

print("✅ Step 9: تم تنظيف الرموز غير المنطقية من المدن.")

Empty DataFrame
Columns: [city, count]
Index: []

✅ Step 9: تم تنظيف الرموز غير المنطقية من المدن.

In [26]:
import duckdb

con = duckdb.connect(
    database="/tmp/enterprise_warehouse.duckdb"
)

con.execute("""
CREATE OR REPLACE VIEW main.v_step9_clean_phones AS

SELECT
    * EXCLUDE (phone_number, city),

    CASE

        WHEN phone_number IS NULL
          OR LOWER(TRIM(phone_number))
                IN ('', 'null', 'nan', 'none', 'n/a')
        THEN NULL

        WHEN REGEXP_REPLACE(
                TRIM(phone_number),
                '[^0-9]',
                '',
                'g'
             ) LIKE '00249%'
             AND LENGTH(
                REGEXP_REPLACE(
                    TRIM(phone_number),
                    '[^0-9]',
                    '',
                    'g'
                )
             ) = 14
        THEN
            '+249' ||
            SUBSTR(
                REGEXP_REPLACE(
                    TRIM(phone_number),
                    '[^0-9]',
                    '',
                    'g'
                ),
                6
            )

        WHEN REGEXP_REPLACE(
                TRIM(phone_number),
                '[^0-9]',
                '',
                'g'
             ) LIKE '249%'
             AND LENGTH(
                REGEXP_REPLACE(
                    TRIM(phone_number),
                    '[^0-9]',
                    '',
                    'g'
                )
             ) = 12
        THEN
            '+' ||
            REGEXP_REPLACE(
                TRIM(phone_number),
                '[^0-9]',
                '',
                'g'
            )

        WHEN REGEXP_REPLACE(
                TRIM(phone_number),
                '[^0-9]',
                '',
                'g'
             ) LIKE '09%'
             AND LENGTH(
                REGEXP_REPLACE(
                    TRIM(phone_number),
                    '[^0-9]',
                    '',
                    'g'
                )
             ) = 10
        THEN
            '+249' ||
            SUBSTR(
                REGEXP_REPLACE(
                    TRIM(phone_number),
                    '[^0-9]',
                    '',
                    'g'
                ),
                2
            )

        ELSE NULL

    END AS clean_phone,

    city_clean AS city

FROM main.v_step9_clean_chars;
""")

print("✅ Step 9: phones and city cleaning connected to the main pipeline.")

✅ Step 9: phones and city cleaning connected to the main pipeline.

In [27]:
import duckdb

con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

# فحص القيم التي ليست JSON صحيح
df_bad_json = con.execute("""
SELECT device_info, COUNT(*) as count
FROM main.v_step9_clean_phones
WHERE device_info IS NOT NULL 
  AND device_info != ''
  AND json_valid(device_info) = FALSE -- اعزل فقط غير الصالح هندسياً
GROUP BY device_info;
""").df()

display(df_bad_json)

  device_info    count
0        NULL  1959136

In [28]:
import duckdb

con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

con.execute("""
CREATE OR REPLACE VIEW main.v_step10_parsed_json AS

WITH validated_json AS (

    SELECT
        *,

        CASE
            WHEN device_info IS NOT NULL
                 AND TRIM(device_info) != ''
                 AND LOWER(TRIM(device_info))
                     NOT IN ('null', 'nan', 'none')
                 AND json_valid(device_info)
            THEN device_info

            ELSE NULL
        END AS valid_device_json

    FROM main.v_step9_clean_phones
)

SELECT
    *,

    json_extract_string(
        valid_device_json,
        '$.os'
    ) AS device_os,

    json_extract_string(
        valid_device_json,
        '$.app_version'
    ) AS device_app_version

FROM validated_json;
""")

df_device_info = con.execute("""
SELECT
    trip_id,
    device_info,
    device_os,
    device_app_version
FROM main.v_step10_parsed_json
LIMIT 10;
""").df()

display(df_device_info)

print("✅ Step 10: تم فحص JSON واستخراج البيانات بأمان.")

,trip_id,device_info,device_os,device_app_version
0,TRIP_1000008,"{""os"": ""Android"", ""app_version"": ""5.1.2""}",Android,5.1.2
1,TRIP_1000051,"{""os"": ""Android"", ""app_version"": ""5.1.2""}",Android,5.1.2
2,TRIP_100014,{},None,None
3,TRIP_1000230,"{""os"": ""Android"", ""app_version"": ""5.1.2""}",Android,5.1.2
4,TRIP_1000283,{},None,None
5,TRIP_1000303,NULL,None,None
6,TRIP_1000727,"{""os"": ""Huawei"", ""app_version"": ""4.9.0""}",Huawei,4.9.0
7,TRIP_1000826,"{""os"": ""iOS"", ""app_version"": ""5.1.0""}",iOS,5.1.0
8,TRIP_1001047,"{""os"": ""Huawei"", ""app_version"": ""4.9.0""}",Huawei,4.9.0
9,TRIP_100127,"{""os"": ""Huawei"", ""app_version"": ""4.9.0""}",Huawei,4.9.0

✅ Step 10: تم فحص JSON واستخراج البيانات بأمان.

In [29]:
import duckdb

con = duckdb.connect(database="/tmp/enterprise_warehouse.duckdb")

# الفحص المطور لتحديد الرحلات اليتيمة ومقاومة كافة تلاعبات النصوص
df_orphaned = con.execute("""
SELECT trip_id, driver_id, customer_id
FROM main.v_step10_parsed_json
WHERE 
   -- فحص السائق بعد توحيد حالة الأحرف وإزالة المسافات
   driver_id IS NULL 
   OR TRIM(driver_id) = '' 
   OR LOWER(TRIM(driver_id)) IN ('null', 'nan', 'none')
   
   -- فحص العميل بعد توحيد حالة الأحرف وإزالة المسافات
   OR customer_id IS NULL 
   OR TRIM(customer_id) = '' 
   OR LOWER(TRIM(customer_id)) IN ('null', 'nan', 'none');
""").df()

print(f"✅ عدد السجلات اليتيمة المكتشفة بدقة: {len(df_orphaned)}")
display(df_orphaned)

✅ عدد السجلات اليتيمة المكتشفة بدقة: 0

Empty DataFrame
Columns: [trip_id, driver_id, customer_id]
Index: []

In [30]:
import duckdb

con = duckdb.connect(
    database="/tmp/enterprise_warehouse.duckdb"
)

con.execute("""
CREATE OR REPLACE TABLE main.ref_drivers AS
SELECT
    'DRV_' || CAST(i AS VARCHAR) AS driver_id
FROM range(1, 1001) AS t(i);
""")

con.execute("""
CREATE OR REPLACE TABLE main.ref_customers AS
SELECT
    'CST_' || CAST(i AS VARCHAR) AS customer_id
FROM range(1, 5001) AS t(i);
""")

print("✅ Reference tables created.")

display(
    con.execute("""
        SELECT
            'drivers' AS reference_name,
            COUNT(*) AS rows_count
        FROM main.ref_drivers

        UNION ALL

        SELECT
            'customers',
            COUNT(*)
        FROM main.ref_customers;
    """).df()
)

✅ Reference tables created.

  reference_name  rows_count
0        drivers        1000
1      customers        5000

In [31]:
import duckdb

con = duckdb.connect(
    database="/tmp/enterprise_warehouse.duckdb"
)

con.execute("""
CREATE OR REPLACE TABLE main.fct_trips AS

WITH final_clean AS (

    SELECT
        trip_id,
        driver_id,
        customer_id,
        start_time,
        end_time,
        distance_km,
        fare_amount,
        price_per_km,

        TRIM(
            REGEXP_REPLACE(
                city,
                '[^a-zA-Z ]',
                '',
                'g'
            )
        ) AS city_clean,

        status,
        clean_phone,
        device_os,
        device_app_version

    FROM main.v_step10_parsed_json
)

SELECT
    trip_id,
    driver_id,
    customer_id,
    start_time,
    end_time,
    distance_km,
    fare_amount,
    price_per_km,
    city_clean AS city,
    status,
    clean_phone AS phone_number,
    device_os,
    device_app_version

FROM final_clean

WHERE
    trip_id IS NOT NULL
    AND TRIM(trip_id) != ''
    AND LOWER(TRIM(trip_id))
        NOT IN ('null', 'nan', 'none')

    AND driver_id IS NOT NULL
    AND TRIM(driver_id) != ''

    AND customer_id IS NOT NULL
    AND TRIM(customer_id) != ''

    AND start_time IS NOT NULL

    AND end_time IS NOT NULL
    AND end_time >= start_time

    AND distance_km IS NOT NULL
    AND distance_km > 0

    AND fare_amount IS NOT NULL
    AND fare_amount >= 0

    AND city_clean IS NOT NULL
    AND TRIM(city_clean) != '';
""")

final_rows = con.execute("""
SELECT COUNT(*)
FROM main.fct_trips;
""").fetchone()[0]

print(
    f"✅ fct_trips created successfully: {final_rows:,} rows."
)

display(
    con.execute("""
        SELECT *
        FROM main.fct_trips
        LIMIT 10;
    """).df()
)

✅ fct_trips created successfully: 9,630,970 rows.

,trip_id,driver_id,customer_id,start_time,end_time,distance_km,fare_amount,price_per_km,city,status,phone_number,device_os,device_app_version
0,TRIP_5696061,DRV_894,CST_1457,2026-01-07 14:13:26,2026-01-07 14:41:26,45.28,334.26,7.382067,Port Sudan,None,+249912345678,None,None
1,TRIP_5696293,DRV_839,CST_1958,2026-01-07 14:13:49,2026-01-07 14:57:49,283.52,1122.36,3.958663,Khartoum,COMPLETED,+249912345678,None,None
2,TRIP_5696546,DRV_837,CST_2281,2026-01-07 14:14:14,2026-01-07 14:24:14,345.35,995.31,2.882033,Port Sudan,None,+249912345678,None,None
3,TRIP_5696642,DRV_568,CST_4980,2026-01-07 14:14:24,2026-01-07 14:25:24,165.88,122.61,0.739149,Port Sudan,COMPLETED,+249912345678,None,None
4,TRIP_569672,DRV_620,CST_4730,2026-01-01 15:49:27,2026-01-01 16:01:27,63.29,305.58,4.828251,Khartoum,FAILED,None,None,None
5,TRIP_5696868,DRV_993,CST_4517,2026-01-07 14:14:46,2026-01-07 14:34:46,399.49,1386.63,3.471001,Khartoum,FAILED,None,Huawei,4.9.0
6,TRIP_5696970,DRV_791,CST_873,2026-01-07 14:14:57,2026-01-07 14:22:57,46.38,100.33,2.163217,Khartoum,COMPLETED,+249912345678,Huawei,4.9.0
7,TRIP_5697073,DRV_179,CST_1170,2026-01-07 14:15:07,2026-01-07 14:50:07,14.68,85.49,5.823569,Bahri,None,None,Android,5.1.2
8,TRIP_5697258,DRV_645,CST_1898,2026-01-07 14:15:25,2026-01-07 14:55:25,292.17,901.89,3.086867,Port Sudan,FAILED,+249912345678,Android,5.1.2
9,TRIP_5697381,DRV_531,CST_3977,2026-01-07 14:15:38,2026-01-07 14:57:38,141.01,762.37,5.406496,Omdurman,COMPLETED,None,None,None

In [32]:
import duckdb

con = duckdb.connect(
    database="/tmp/enterprise_warehouse.duckdb"
)

con.execute("""
CREATE OR REPLACE TABLE main.fct_trips_final AS

SELECT
    f.*

FROM main.fct_trips f

INNER JOIN main.ref_drivers d
    ON TRIM(f.driver_id) = TRIM(d.driver_id)

INNER JOIN main.ref_customers c
    ON TRIM(f.customer_id) = TRIM(c.customer_id)

WHERE

    -- =====================================================
    -- Trip ID
    -- =====================================================

    f.trip_id IS NOT NULL
    AND TRIM(f.trip_id) != ''

    -- =====================================================
    -- Driver / Customer
    -- =====================================================

    AND f.driver_id IS NOT NULL
    AND TRIM(f.driver_id) != ''

    AND f.customer_id IS NOT NULL
    AND TRIM(f.customer_id) != ''

    -- =====================================================
    -- Time
    -- =====================================================

    AND f.start_time IS NOT NULL
    AND f.start_time <= NOW()

    AND f.end_time IS NOT NULL
    AND f.end_time >= f.start_time

    -- =====================================================
    -- Distance
    -- =====================================================

    AND f.distance_km IS NOT NULL
    AND f.distance_km > 0

    -- =====================================================
    -- Fare
    -- =====================================================

    AND f.fare_amount IS NOT NULL
    AND f.fare_amount >= 0

    -- =====================================================
    -- Status
    -- =====================================================

    AND f.status IS NOT NULL
    AND LOWER(TRIM(f.status))
        IN (
            'completed',
            'cancelled',
            'failed'
        )

    -- =====================================================
    -- City
    -- =====================================================

    AND f.city IS NOT NULL
    AND LOWER(TRIM(f.city))
        IN (
            'khartoum',
            'omdurman',
            'bahri',
            'port sudan'
        )

QUALIFY ROW_NUMBER() OVER (
    PARTITION BY TRIM(f.trip_id)
    ORDER BY f.start_time DESC NULLS LAST
) = 1;
""")

final_stats = con.execute("""
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT trip_id) AS unique_trip_ids
FROM main.fct_trips_final;
""").df()

display(final_stats)

print("✅ fct_trips_final created successfully.")

   total_rows  unique_trip_ids
0     5960965          5960965

✅ fct_trips_final created successfully.

In [33]:
import duckdb

con = duckdb.connect(
    database="/tmp/enterprise_warehouse.duckdb"
)

con.execute("""
CREATE OR REPLACE TABLE main.test_results (
    test_name VARCHAR,
    expected VARCHAR,
    actual VARCHAR,
    status VARCHAR,
    run_time TIMESTAMP
);
""")

# ============================================================
# 1. trip_id uniqueness
# ============================================================

con.execute("""
INSERT INTO main.test_results
SELECT
    'Uniqueness Check (trip_id)',
    '0 duplicates',
    CAST(COUNT(*) AS VARCHAR) || ' duplicates',
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END,
    CURRENT_TIMESTAMP
FROM (
    SELECT trip_id
    FROM main.fct_trips_final
    GROUP BY trip_id
    HAVING COUNT(*) > 1
);
""")

# ============================================================
# 2. Required IDs
# ============================================================

con.execute("""
INSERT INTO main.test_results
SELECT
    'Required IDs Check',
    '0 invalid rows',
    CAST(COUNT(*) AS VARCHAR) || ' invalid rows',
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END,
    CURRENT_TIMESTAMP
FROM main.fct_trips_final
WHERE trip_id IS NULL OR TRIM(trip_id) = ''
   OR driver_id IS NULL OR TRIM(driver_id) = ''
   OR customer_id IS NULL OR TRIM(customer_id) = '';
""")

# ============================================================
# 3. Driver reference integrity
# ============================================================

con.execute("""
INSERT INTO main.test_results
SELECT
    'Driver Reference Integrity',
    '0 invalid references',
    CAST(COUNT(*) AS VARCHAR) || ' invalid references',
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END,
    CURRENT_TIMESTAMP
FROM main.fct_trips_final f
LEFT JOIN main.ref_drivers d
    ON TRIM(f.driver_id) = TRIM(d.driver_id)
WHERE d.driver_id IS NULL;
""")

# ============================================================
# 4. Customer reference integrity
# ============================================================

con.execute("""
INSERT INTO main.test_results
SELECT
    'Customer Reference Integrity',
    '0 invalid references',
    CAST(COUNT(*) AS VARCHAR) || ' invalid references',
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END,
    CURRENT_TIMESTAMP
FROM main.fct_trips_final f
LEFT JOIN main.ref_customers c
    ON TRIM(f.customer_id) = TRIM(c.customer_id)
WHERE c.customer_id IS NULL;
""")

# ============================================================
# 5. Timestamp
# ============================================================

con.execute("""
INSERT INTO main.test_results
SELECT
    'Timestamp Check',
    '0 invalid intervals',
    CAST(COUNT(*) AS VARCHAR) || ' invalid intervals',
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END,
    CURRENT_TIMESTAMP
FROM main.fct_trips_final
WHERE start_time IS NULL
   OR end_time IS NULL
   OR end_time < start_time
   OR start_time > NOW();
""")

# ============================================================
# 6. Distance
# ============================================================

con.execute("""
INSERT INTO main.test_results
SELECT
    'Distance Check',
    '0 invalid values',
    CAST(COUNT(*) AS VARCHAR) || ' invalid values',
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END,
    CURRENT_TIMESTAMP
FROM main.fct_trips_final
WHERE distance_km IS NULL
   OR distance_km <= 0;
""")

# ============================================================
# 7. Fare
# ============================================================

con.execute("""
INSERT INTO main.test_results
SELECT
    'Fare Check',
    '0 invalid values',
    CAST(COUNT(*) AS VARCHAR) || ' invalid values',
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END,
    CURRENT_TIMESTAMP
FROM main.fct_trips_final
WHERE fare_amount IS NULL
   OR fare_amount < 0;
""")

# ============================================================
# 8. Status
# ============================================================

con.execute("""
INSERT INTO main.test_results
SELECT
    'Status Check',
    '0 invalid statuses',
    CAST(COUNT(*) AS VARCHAR) || ' invalid statuses',
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END,
    CURRENT_TIMESTAMP
FROM main.fct_trips_final
WHERE status IS NULL
   OR LOWER(TRIM(status))
        NOT IN ('completed', 'cancelled', 'failed');
""")

# ============================================================
# 9. City
# ============================================================

con.execute("""
INSERT INTO main.test_results
SELECT
    'City Check',
    '0 invalid cities',
    CAST(COUNT(*) AS VARCHAR) || ' invalid cities',
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END,
    CURRENT_TIMESTAMP
FROM main.fct_trips_final
WHERE city IS NULL
   OR LOWER(TRIM(city))
        NOT IN ('khartoum', 'omdurman', 'bahri', 'port sudan');
""")

# ============================================================
# 10. Phone
# ============================================================

con.execute("""
INSERT INTO main.test_results
SELECT
    'Phone Format Check',
    '0 invalid phones',
    CAST(COUNT(*) AS VARCHAR) || ' invalid phones',
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END,
    CURRENT_TIMESTAMP
FROM main.fct_trips_final
WHERE phone_number IS NOT NULL
  AND NOT REGEXP_MATCHES(
      phone_number,
      '^\\+2499[0-9]{8}$'
  );
""")

# ============================================================
# 11. JSON
# ============================================================

con.execute("""
INSERT INTO main.test_results
SELECT
    'JSON Validation Check',
    '0 invalid JSON values',
    CAST(COUNT(*) AS VARCHAR) || ' invalid JSON values',
    CASE
        WHEN COUNT(*) = 0 THEN 'PASS'
        ELSE 'FAIL'
    END,
    CURRENT_TIMESTAMP
FROM main.v_step10_parsed_json
WHERE device_info IS NOT NULL
  AND TRIM(device_info) != ''
  AND LOWER(TRIM(device_info))
        NOT IN ('null', 'nan', 'none')
  AND json_valid(device_info) = FALSE;
""")

print("✅ Final data-quality tests executed.")

display(
    con.execute("""
        SELECT
            test_name,
            expected,
            actual,
            status,
            run_time
        FROM main.test_results
        ORDER BY test_name;
    """).df()
)

✅ Final data-quality tests executed.

,test_name,expected,actual,status,run_time
0,City Check,0 invalid cities,0 invalid cities,PASS,2026-08-24 13:59:41.495216
1,Customer Reference Integrity,0 invalid references,0 invalid references,PASS,2026-08-24 13:59:40.823315
2,Distance Check,0 invalid values,0 invalid values,PASS,2026-08-24 13:59:41.400890
3,Driver Reference Integrity,0 invalid references,0 invalid references,PASS,2026-08-24 13:59:40.774435
4,Fare Check,0 invalid values,0 invalid values,PASS,2026-08-24 13:59:41.405417
5,JSON Validation Check,0 invalid JSON values,0 invalid JSON values,PASS,2026-08-24 13:59:41.762671
6,Phone Format Check,0 invalid phones,0 invalid phones,PASS,2026-08-24 13:59:41.575698
7,Required IDs Check,0 invalid rows,0 invalid rows,PASS,2026-08-24 13:59:40.399428
8,Status Check,0 invalid statuses,0 invalid statuses,PASS,2026-08-24 13:59:41.409878
9,Timestamp Check,0 invalid intervals,0 invalid intervals,PASS,2026-08-24 13:59:40.919676
10,Uniqueness Check (trip_id),0 duplicates,0 duplicates,PASS,2026-08-24 13:59:39.746391

In [34]:
# ============================================================
# FINAL DATA QUALITY GATE
# إيقاف الـ Pipeline إذا فشل أي اختبار
# ============================================================

failed_tests = con.execute("""
    SELECT COUNT(*)
    FROM main.test_results
    WHERE status = 'FAIL';
""").fetchone()[0]

if failed_tests > 0:

    print(f"❌ Pipeline متوقف: {failed_tests} اختبار فشل.\n")

    print("الاختبارات الفاشلة:")
    
    display(
        con.execute("""
            SELECT
                test_name,
                expected,
                actual,
                status,
                run_time
            FROM main.test_results
            WHERE status = 'FAIL'
            ORDER BY test_name;
        """).df()
    )

    raise RuntimeError(
        f"Pipeline متوقف بسبب {failed_tests} اختبار فاشل. "
        "راجع نتائج اختبارات الجودة أعلاه."
    )

else:

    print(
        "✅ جميع اختبارات الجودة PASS. "
        "البيانات جاهزة للطبقة التحليلية."
    )

✅ جميع اختبارات الجودة PASS. البيانات جاهزة للطبقة التحليلية.

In [46]:
import duckdb

con = duckdb.connect(
    database="/tmp/enterprise_warehouse.duckdb"
)

# ============================================================
# BUSINESS LAYER
# ============================================================

# ------------------------------------------------------------
# Customer Business Table
# One row per customer
# ------------------------------------------------------------

con.execute("""
CREATE OR REPLACE TABLE main.biz_customer_segmentation AS

SELECT
    customer_id,

    ANY_VALUE(phone_number) AS phone_number,

    COUNT(*) AS total_trips,

    COUNT(*) FILTER (
        WHERE status = 'COMPLETED'
    ) AS completed_trips,

    COUNT(*) FILTER (
        WHERE status = 'CANCELLED'
    ) AS cancelled_trips,

    COUNT(*) FILTER (
        WHERE status = 'FAILED'
    ) AS failed_trips,

    ROUND(
        SUM(fare_amount),
        2
    ) AS total_spend,

    ROUND(
        AVG(fare_amount),
        2
    ) AS average_fare,

    ROUND(
        AVG(distance_km),
        2
    ) AS average_distance,

    CASE
        WHEN SUM(fare_amount) >= 50000
          OR COUNT(*) >= 50
        THEN 'VIP'

        WHEN SUM(fare_amount) >= 10000
        THEN 'REGULAR'

        ELSE 'LOW_FREQUENT'
    END AS customer_tier

FROM main.fct_trips_final

GROUP BY customer_id;
""")

# ------------------------------------------------------------
# Driver Business Table
# One row per driver
# ------------------------------------------------------------

con.execute("""
CREATE OR REPLACE TABLE main.biz_driver_performance AS

SELECT
    driver_id,

    COUNT(*) AS total_trips,

    COUNT(*) FILTER (
        WHERE status = 'COMPLETED'
    ) AS completed_trips,

    COUNT(*) FILTER (
        WHERE status = 'CANCELLED'
    ) AS cancelled_trips,

    COUNT(*) FILTER (
        WHERE status = 'FAILED'
    ) AS failed_trips,

    ROUND(
        SUM(
            CASE
                WHEN status = 'COMPLETED'
                THEN fare_amount
                ELSE 0
            END
        ),
        2
    ) AS total_earnings,

    ROUND(
        AVG(
            CASE
                WHEN status = 'COMPLETED'
                THEN distance_km
            END
        ),
        2
    ) AS avg_trip_distance,

    ROUND(
        AVG(
            CASE
                WHEN status = 'COMPLETED'
                THEN fare_amount
            END
        ),
        2
    ) AS avg_completed_fare

FROM main.fct_trips_final

GROUP BY driver_id;
""")

# ============================================================
# STAR SCHEMA
# ============================================================

# ------------------------------------------------------------
# Customer Dimension
# One row per customer
# ------------------------------------------------------------

con.execute("""
CREATE OR REPLACE TABLE main.dim_customer AS

SELECT
    customer_id,
    phone_number,
    total_trips,
    completed_trips,
    cancelled_trips,
    failed_trips,
    total_spend,
    average_fare,
    average_distance,
    customer_tier

FROM main.biz_customer_segmentation;
""")

# ------------------------------------------------------------
# Driver Dimension
# One row per driver
# ------------------------------------------------------------

con.execute("""
CREATE OR REPLACE TABLE main.dim_driver AS

SELECT
    driver_id,
    total_trips,
    completed_trips,
    cancelled_trips,
    failed_trips,
    total_earnings,
    avg_trip_distance,
    avg_completed_fare

FROM main.biz_driver_performance;
""")

# ------------------------------------------------------------
# Location Dimension
# One row per city
# ------------------------------------------------------------

con.execute("""
CREATE OR REPLACE TABLE main.dim_location AS

SELECT
    city,

    COUNT(*) AS total_trips,

    COUNT(*) FILTER (
        WHERE status = 'COMPLETED'
    ) AS completed_trips,

    COUNT(*) FILTER (
        WHERE status = 'CANCELLED'
    ) AS cancelled_trips,

    COUNT(*) FILTER (
        WHERE status = 'FAILED'
    ) AS failed_trips,

    ROUND(
        SUM(fare_amount),
        2
    ) AS total_revenue,

    ROUND(
        AVG(fare_amount),
        2
    ) AS average_fare,

    ROUND(
        AVG(distance_km),
        2
    ) AS average_distance

FROM main.fct_trips_final

GROUP BY city;
""")

# ------------------------------------------------------------
# Daily Revenue Fact
# One row per date + city
# ------------------------------------------------------------

con.execute("""
CREATE OR REPLACE TABLE main.fact_daily_revenue AS

SELECT
    CAST(start_time AS DATE) AS trip_date,

    city,

    COUNT(*) AS daily_trips,

    COUNT(*) FILTER (
        WHERE status = 'COMPLETED'
    ) AS completed_trips,

    COUNT(*) FILTER (
        WHERE status = 'CANCELLED'
    ) AS cancelled_trips,

    COUNT(*) FILTER (
        WHERE status = 'FAILED'
    ) AS failed_trips,

    ROUND(
        SUM(fare_amount),
        2
    ) AS daily_revenue,

    ROUND(
        AVG(fare_amount),
        2
    ) AS average_fare

FROM main.fct_trips_final

GROUP BY
    CAST(start_time AS DATE),
    city;
""")

print("✅ Business Layer + Star Schema created successfully.")

display(
    con.execute("""
        SELECT
            'biz_customer_segmentation' AS table_name,
            COUNT(*) AS rows_count
        FROM main.biz_customer_segmentation

        UNION ALL

        SELECT
            'biz_driver_performance',
            COUNT(*)
        FROM main.biz_driver_performance

        UNION ALL

        SELECT
            'dim_customer',
            COUNT(*)
        FROM main.dim_customer

        UNION ALL

        SELECT
            'dim_driver',
            COUNT(*)
        FROM main.dim_driver

        UNION ALL

        SELECT
            'dim_location',
            COUNT(*)
        FROM main.dim_location

        UNION ALL

        SELECT
            'fact_daily_revenue',
            COUNT(*)
        FROM main.fact_daily_revenue;
    """).df()
)

✅ Business Layer + Star Schema created successfully.

                  table_name  rows_count
0  biz_customer_segmentation        5000
1     biz_driver_performance        1000
2               dim_customer        5000
3                 dim_driver        1000
4               dim_location           4
5         fact_daily_revenue          48

In [47]:
import duckdb

con = duckdb.connect(
    database="/tmp/enterprise_warehouse.duckdb"
)

# ============================================================
# 1. Driver Ranking
# ============================================================

con.execute("""
CREATE OR REPLACE TABLE main.analytical_driver_insights AS

SELECT
    driver_id,
    completed_trips,
    total_earnings,

    RANK() OVER (
        ORDER BY total_earnings DESC
    ) AS earnings_rank,

    NTILE(4) OVER (
        ORDER BY completed_trips DESC
    ) AS activity_quartile

FROM main.biz_driver_performance;
""")

# ============================================================
# 2. Daily Revenue Growth
# ============================================================

con.execute("""
CREATE OR REPLACE TABLE main.analytical_daily_growth AS

WITH daily AS (

    SELECT
        city,
        trip_date,
        daily_revenue,

        LAG(daily_revenue) OVER (
            PARTITION BY city
            ORDER BY trip_date
        ) AS previous_day_revenue

    FROM main.fact_daily_revenue
)

SELECT
    city,
    trip_date,
    daily_revenue,
    previous_day_revenue,

    CASE
        WHEN previous_day_revenue IS NULL
             OR previous_day_revenue = 0
        THEN NULL

        ELSE ROUND(
            (
                daily_revenue - previous_day_revenue
            )
            / previous_day_revenue
            * 100,
            2
        )
    END AS growth_percentage

FROM daily;
""")

print("✅ Advanced analytical tables created successfully.")

display(
    con.execute("""
        SELECT
            'analytical_driver_insights' AS table_name,
            COUNT(*) AS rows_count
        FROM main.analytical_driver_insights

        UNION ALL

        SELECT
            'analytical_daily_growth',
            COUNT(*)
        FROM main.analytical_daily_growth;
    """).df()
)

✅ Advanced analytical tables created successfully.

                   table_name  rows_count
0  analytical_driver_insights        1000
1     analytical_daily_growth          48

In [48]:
import duckdb

con = duckdb.connect(
    database="/tmp/enterprise_warehouse.duckdb"
)

summary = con.execute("""
SELECT
    'fct_trips_final' AS table_name,
    COUNT(*) AS rows_count
FROM main.fct_trips_final

UNION ALL

SELECT
    'biz_customer_segmentation',
    COUNT(*)
FROM main.biz_customer_segmentation

UNION ALL

SELECT
    'biz_driver_performance',
    COUNT(*)
FROM main.biz_driver_performance

UNION ALL

SELECT
    'dim_customer',
    COUNT(*)
FROM main.dim_customer

UNION ALL

SELECT
    'dim_driver',
    COUNT(*)
FROM main.dim_driver

UNION ALL

SELECT
    'dim_location',
    COUNT(*)
FROM main.dim_location

UNION ALL

SELECT
    'fact_daily_revenue',
    COUNT(*)
FROM main.fact_daily_revenue

UNION ALL

SELECT
    'analytical_driver_insights',
    COUNT(*)
FROM main.analytical_driver_insights

UNION ALL

SELECT
    'analytical_daily_growth',
    COUNT(*)
FROM main.analytical_daily_growth;
""").df()

display(summary)

print("✅ Final reconciliation completed.")

                   table_name  rows_count
0             fct_trips_final     5960965
1   biz_customer_segmentation        5000
2      biz_driver_performance        1000
3                dim_customer        5000
4                  dim_driver        1000
5                dim_location           4
6          fact_daily_revenue          48
7  analytical_driver_insights        1000
8     analytical_daily_growth          48

✅ Final reconciliation completed.

In [49]:
import duckdb
from pathlib import Path

con = duckdb.connect(
    database="/tmp/enterprise_warehouse.duckdb"
)

# ============================================================
# FINAL EXPORT DIRECTORY
# ============================================================

export_dir = Path("final_exports")
export_dir.mkdir(
    parents=True,
    exist_ok=True
)

exports = {
    "final_clean_trips.csv": "fct_trips_final",
    "customers.csv": "dim_customer",
    "drivers.csv": "dim_driver",
    "locations.csv": "dim_location",
    "daily_revenue.csv": "fact_daily_revenue",
    "driver_insights.csv": "analytical_driver_insights",
    "daily_growth.csv": "analytical_daily_growth",

    "final_clean_trips.parquet": "fct_trips_final",
    "customers.parquet": "dim_customer",
    "drivers.parquet": "dim_driver",
    "locations.parquet": "dim_location",
    "daily_revenue.parquet": "fact_daily_revenue",
    "driver_insights.parquet": "analytical_driver_insights",
    "daily_growth.parquet": "analytical_daily_growth"
}

for filename, table_name in exports.items():

    output_path = export_dir / filename

    # حذف نسخة سابقة داخل مجلد التصدير فقط
    if output_path.exists():
        output_path.unlink()

    if filename.endswith(".csv"):

        con.execute(f"""
            COPY main."{table_name}"
            TO '{output_path.as_posix()}'
            (
                HEADER,
                DELIMITER ','
            );
        """)

    else:

        con.execute(f"""
            COPY main."{table_name}"
            TO '{output_path.as_posix()}'
            (
                FORMAT PARQUET,
                COMPRESSION 'ZSTD'
            );
        """)

    print(f"✅ Exported: {output_path}")

print("✅ ALL FINAL EXPORTS COMPLETED.")

✅ Exported: final_exports/final_clean_trips.csv
✅ Exported: final_exports/customers.csv
✅ Exported: final_exports/drivers.csv
✅ Exported: final_exports/locations.csv
✅ Exported: final_exports/daily_revenue.csv
✅ Exported: final_exports/driver_insights.csv
✅ Exported: final_exports/daily_growth.csv
✅ Exported: final_exports/final_clean_trips.parquet
✅ Exported: final_exports/customers.parquet
✅ Exported: final_exports/drivers.parquet
✅ Exported: final_exports/locations.parquet
✅ Exported: final_exports/daily_revenue.parquet
✅ Exported: final_exports/driver_insights.parquet
✅ Exported: final_exports/daily_growth.parquet
✅ ALL FINAL EXPORTS COMPLETED.

In [50]:
con.execute("""
CREATE TABLE IF NOT EXISTS main.pipeline_execution_logs (
    execution_id BIGINT,
    pipeline_name VARCHAR,
    run_date TIMESTAMP,
    rows_processed BIGINT,
    status VARCHAR
);
""")

total_rows_processed = con.execute("""
SELECT COUNT(*)
FROM main.fct_trips_final;
""").fetchone()[0]

next_execution_id = con.execute("""
SELECT
    COALESCE(MAX(execution_id), 0) + 1
FROM main.pipeline_execution_logs;
""").fetchone()[0]

con.execute("""
INSERT INTO main.pipeline_execution_logs
VALUES (?, ?, CURRENT_TIMESTAMP, ?, ?);
""", [
    next_execution_id,
    'Enterprise_Trips_Pipeline_FINAL',
    total_rows_processed,
    'SUCCESS'
])

print("✅ تم تسجيل تشغيل الـPipeline.")

display(
    con.execute("""
        SELECT *
        FROM main.pipeline_execution_logs
        ORDER BY execution_id DESC
        LIMIT 5;
    """).df()
)

✅ تم تسجيل تشغيل الـPipeline.

,execution_id,pipeline_name,run_date,rows_processed,status
0,3,Enterprise_Trips_Pipeline_FINAL,2026-08-24 14:11:15.480500,5960965,SUCCESS
1,2,Enterprise_Trips_Pipeline,2026-08-24 14:04:08.397007,5960965,SUCCESS
2,1,Enterprise_Trips_Pipeline,2026-08-24 13:59:47.752297,5960965,SUCCESS

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=ce06c312-672e-4725-a824-86d9048dc9cf' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' />
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>